---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/tduarte/duarte-blue
name: duarte-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: dnf
        destination: /etc/yum.repos.d/
  - type: dnf
    repos:
      files:
        - 1password.repo
        - https://negativo17.org/repos/fedora-steam.repo
      copr:
        - sneexy/zen-browser
        - trixieua/mutter-patched
        # - pgdev/ghostty
        - che/zed
      keys:
        - https://downloads.1password.com/linux/keys/1password.asc
    optfix: # performs symlinking for `/opt/` to allow certain packages to install
      - zen-browser
      - 1Password
    install:
      skip-unavailable: true # skip unavailable packages
      install-weak-deps: false
      packages:
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
        - 1password
        # - ghostty
        - zen-browser
        - zed
        - steam
        - discord
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.github.Foldex.AdwSteamGtk
        - com.github.tchx84.Flatseal
        - com.vysp3r.ProtonPlus
        - io.github.shiftey.Desktop
        - com.mattjakeman.ExtensionManager
        - com.brave.Browser
        - net.nokyan.Resources
        - page.kramo.Cartridges
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
